.skip_on_watch: &skip_on_watch
  rules:
    - if: $WATCH
      when: never
    - when: on_success

.e2e-test-template:
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/aval:${CI_COMMIT_REF_NAME}
  <<: *skip_on_watch
  variables:
    TARGET_BUILD_TYPE: "release"
    AVAL_VERBOSE: "true"
    GIT_STRATEGY: none
  script:
    - /usr/local/bin/entrypoint.sh "docker run -e SOC_UDT=$SOC_UDT --privileged --pid host
      -v /var/run/docker.sock:/var/run/docker.sock -v /home/torizon:/home/torizon
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/aval-e2e-tests:${CI_COMMIT_REF_NAME} /suites/run-tests.sh"
      --copy-artifact /home/torizon/report.xml report.xml --delegation-config /aval/delegation_config.toml
      --before "docker system prune --force --all" --run-before-on-host "/aval/host_command.sh device_information.json" 
  artifacts:
    when: always
    reports:
      junit: report.xml
  needs:
    - e2e-tests-container-build
    - unit-test

e2e-test-colibri-imx7d-emmc-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "colibri-imx7d-emmc"

e2e-test-verdin-am62dual-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "verdin-am62dual"

e2e-test-apalis-imx6q-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "apalis-imx6q"

e2e-test-colibri-imx8dx-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "colibri-imx8dx"

e2e-test-verdin-imx8mmq-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "verdin-imx8mmq"

e2e-test-verdin-imx8mpq-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "verdin-imx8mpq"

e2e-test-colibri-imx7d-emmc-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_UDT: "colibri-imx7d-emmc"

e2e-test-colibri-imx8dx-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_UDT: "colibri-imx8dx"

e2e-test-verdin-am62dual-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_UDT: "verdin-am62dual"

e2e-test-apalis-imx6q-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_UDT: "apalis-imx6q"

e2e-test-apalis-imx8qm-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_UDT: "apalis-imx8qm"

e2e-test-colibri-imx8dx-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_UDT: "colibri-imx8dx"

e2e-test-verdin-imx8mmq-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_UDT: "verdin-imx8mmq"

e2e-test-verdin-imx8mpq-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_UDT: "verdin-imx8mpq"

e2e-test-verdin-imx8mpq-npu-release:
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/aval:${CI_COMMIT_REF_NAME}
  <<: *skip_on_watch
  variables:
    TARGET_BUILD_TYPE: "release"
    AVAL_VERBOSE: "true"
  script:
    - /usr/local/bin/entrypoint.sh "docker run -e SOC_UDT=$SOC_UDT --privileged --pid host
      -v /var/run/docker.sock:/var/run/docker.sock -v /home/torizon:/home/torizon
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/aval-e2e-tests:${CI_COMMIT_REF_NAME} /suites/run-tests.sh"
      --copy-artifact /home/torizon/report.xml report.xml --delegation-config /aval/delegation_config.toml
      --device-config /aval/verdin-imx8mpq-npu.toml --before "docker system prune --force --all"
  artifacts:
    when: always
    reports:
      junit: report.xml
  needs:
    - e2e-tests-container-build
    - unit-test

e2e-test-any-arm64-nightly:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_ARCHITECTURE: "arm64"

e2e-test-any-arm-release:
  extends: .e2e-test-template
  variables:
    TARGET_BUILD_TYPE: "nightly"
    SOC_ARCHITECTURE: "arm"