.skip_on_watch: &skip_on_watch
  rules:
    - if: $WATCH
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: on_success

.run_on_watch: &run_on_watch
  rules:
    - if: $WATCH
      when: always
    - when: never

.sentry-container-build:
  image: docker:dind
  <<: *skip_on_watch
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $CI_DOCKER_HUB_PULL_USER -p $CI_DOCKER_HUB_PULL_PASSWORD
    - docker buildx inspect --bootstrap
    - docker buildx build
      --progress=plain
      --push
      --platform linux/$PLATFORM
      -f sentry/Dockerfile
      -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/sentry:${CI_COMMIT_REF_NAME}-$DOCKER_SUFIX .
  needs:
    - lint
    - flake8-lint
    - validate-yaml

sentry-container-build-amd64:
  extends: .sentry-container-build
  tags:
    - saas-linux-small-amd64
  variables:
    PLATFORM: amd64
    DOCKER_SUFIX: amd64

sentry-container-build-arm64:
  extends: .sentry-container-build
  tags:
    - saas-linux-small-arm64
  variables:
    PLATFORM: arm64/v8
    DOCKER_SUFIX: arm64

sentry-container-build-manifest:
  tags:
    - saas-linux-small-amd64
  image: docker:dind
  <<: *skip_on_watch
  needs:
    - sentry-container-build-amd64
    - sentry-container-build-arm64
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx imagetools create -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/sentry:${CI_COMMIT_REF_NAME}
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/sentry:${CI_COMMIT_REF_NAME}-amd64
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/sentry:${CI_COMMIT_REF_NAME}-arm64

.sentry-watch:
  tags:
    - all
  image:
    name: ${CI_REGISTRY}/${CI_PROJECT_PATH}/sentry:${CI_COMMIT_REF_NAME}
    pull_policy: always
  script: cd /sentry && uv run main.py
  variables:
    GIT_STRATEGY: none

sentry-watch:
  extends: .sentry-watch
  <<: *run_on_watch

sentry-watch-push:
  extends: .sentry-watch
  <<: *skip_on_watch
  needs:
    - sentry-container-build-manifest
