.skip_on_watch: &skip_on_watch
  rules:
    - if: $WATCH
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: on_success

.run_on_watch: &run_on_watch
  rules:
    - if: $WATCH
      when: always
    - when: never

sentry-container-build:
  tags:
    - aws-toradex-large
  image: docker:dind
  <<: *skip_on_watch
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $CI_DOCKER_HUB_PULL_USER -p $CI_DOCKER_HUB_PULL_PASSWORD
    - docker buildx create --config ./buildkitd.toml --name multiarch-builder --driver docker-container --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --use
    - docker buildx inspect --bootstrap
    - docker run --privileged --rm tonistiigi/binfmt --install arm64,arm
    - docker buildx build
      --progress=plain
      --push
      --platform linux/arm64/v8,linux/amd64
      -f sentry/Dockerfile
      -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/sentry:${CI_COMMIT_REF_NAME} .
  
sentry-watch:
  tags:
    - all
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/sentry:${CI_COMMIT_REF_NAME}
  <<: *run_on_watch
  script: cd /sentry && uv run main.py
  rules:
    - if: $WATCH
      when: always
    - when: never
  variables:
    GIT_STRATEGY: none
